name = "se-sitrep"
compatibility_date = "2026-05-24"

main = "workers/index.js"

[assets]
directory = "./src"

[[d1_databases]]
binding = "DB"
database_name = "se-sitrep"
database_id = "0ebe709d-150f-4d06-8e6c-a4e2913ce3b7"
migrations_dir = "d1/migrations"
