name = "se-sitrep"
account_id = "bcad3d59d9958df0d7ebfd6048d87772"
compatibility_date = "2026-05-24"

main = "workers/index.js"

[vars]
GITHUB_CLIENT_ID = "Ov23liQ3h7WXkcgkz9F8"

[assets]
directory = "./src"

[[d1_databases]]
binding = "DB"
database_name = "se-sitrep"
database_id = "0ebe709d-150f-4d06-8e6c-a4e2913ce3b7"
migrations_dir = "d1/migrations"
